function readApiBaseUrl() {
  const runtimeValue = typeof window !== 'undefined' ? window.SUB_ELITE_API_BASE_URL || '' : ''
  const metaValue = document.querySelector('meta[name="sub-elite-api-base-url"]')?.content || ''
  const value = String(runtimeValue || metaValue || '').trim().replace(/\/+$/u, '')
  if (value && !value.includes('%SUB_ELITE_API_BASE_URL%')) return value
  return ''
}

export const state = {
  yaml: '',
  originalYaml: '',
  model: null,
  originalModel: null,
  draggedNode: -1,
  expandedNodeKeys: new Set(),
  yamlManualEdit: false,
  subscriptionUrl: '',
  subscriptionApiAvailable: false,
  toastTimer: null,
}

export const invalidEditorInput = Symbol('invalid-editor-input')
export const nodeUiKeys = new WeakMap()
export const apiBaseUrl = readApiBaseUrl()

export const linkProtocolPattern = /(?:^|\s)(vmess|vless|trojan|ss|ssr|socks|socks5|hysteria|hysteria2|hy2|tuic|wireguard):\/\//i

export const input = document.querySelector('#converter-input')
export const fileInput = document.querySelector('#file-input')
export const templateSelect = document.querySelector('#template-select')
export const rulesSelect = document.querySelector('#rules-select')
export const namePatternInput = document.querySelector('#name-pattern-input')
export const filenameInput = document.querySelector('#filename-input')
export const convertButton = document.querySelector('#convert-button')
export const blankConfigButton = document.querySelector('#blank-config-button')
export const sampleButton = document.querySelector('#sample-button')
export const copyButton = document.querySelector('#copy-button')
export const downloadButton = document.querySelector('#download-button')
export const exportFormatSelect = document.querySelector('#export-format-select')
export const formatYamlButton = document.querySelector('#format-yaml-button')
export const validateYamlButton = document.querySelector('#validate-yaml-button')
export const autoFixButton = document.querySelector('#auto-fix-button')
export const toggleDiffButton = document.querySelector('#toggle-diff-button')
export const resetYamlButton = document.querySelector('#reset-yaml-button')
export const createSubscriptionButton = document.querySelector('#create-subscription-button')
export const copySubscriptionButton = document.querySelector('#copy-subscription-button')
export const openSubscriptionLink = document.querySelector('#open-subscription-link')
export const subscriptionUrlInput = document.querySelector('#subscription-url-input')
export const errorBanner = document.querySelector('#error-banner')
export const yamlEditor = document.querySelector('#yaml-editor')
export const diffPanel = document.querySelector('#diff-panel')
export const diffSummary = document.querySelector('#diff-summary')
export const diffViewer = document.querySelector('#diff-viewer')
export const validationBanner = document.querySelector('#validation-banner')
export const validationDetails = document.querySelector('#validation-details')
export const validationIssuesList = document.querySelector('#validation-issues-list')
export const yamlSectionSelect = document.querySelector('#yaml-section-select')
export const yamlSectionPreview = document.querySelector('#yaml-section-preview')
export const warnings = document.querySelector('#warnings')
export const warningsList = document.querySelector('#warnings-list')
export const statTotal = document.querySelector('#stat-total')
export const statConverted = document.querySelector('#stat-converted')
export const statSkipped = document.querySelector('#stat-skipped')
export const nodeList = document.querySelector('#node-list')
export const groupList = document.querySelector('#group-list')
export const groupNameInput = document.querySelector('#group-name-input')
export const groupTypeInput = document.querySelector('#group-type-input')
export const addGroupButton = document.querySelector('#add-group-button')
export const rulesEditor = document.querySelector('#rules-editor')
export const dnsEnable = document.querySelector('#dns-enable')
export const dnsListen = document.querySelector('#dns-listen')
export const dnsCacheAlgorithm = document.querySelector('#dns-cache-algorithm')
export const dnsPreferH3 = document.querySelector('#dns-prefer-h3')
export const dnsUseHosts = document.querySelector('#dns-use-hosts')
export const dnsUseSystemHosts = document.querySelector('#dns-use-system-hosts')
export const dnsRespectRules = document.querySelector('#dns-respect-rules')
export const dnsDefault = document.querySelector('#dns-default')
export const dnsNameservers = document.querySelector('#dns-nameservers')
export const generalPort = document.querySelector('#general-port')
export const generalSocksPort = document.querySelector('#general-socks-port')
export const generalRedirPort = document.querySelector('#general-redir-port')
export const generalTproxyPort = document.querySelector('#general-tproxy-port')
export const generalMixedPort = document.querySelector('#general-mixed-port')
export const generalMode = document.querySelector('#general-mode')
export const generalLogLevel = document.querySelector('#general-log-level')
export const generalBindAddress = document.querySelector('#general-bind-address')
export const generalLanAllowedIps = document.querySelector('#general-lan-allowed-ips')
export const generalLanDisallowedIps = document.querySelector('#general-lan-disallowed-ips')
export const generalAuthentication = document.querySelector('#general-authentication')
export const generalSkipAuthPrefixes = document.querySelector('#general-skip-auth-prefixes')
export const generalInterfaceName = document.querySelector('#general-interface-name')
export const generalRoutingMark = document.querySelector('#general-routing-mark')
export const generalKeepAliveIdle = document.querySelector('#general-keep-alive-idle')
export const generalKeepAliveInterval = document.querySelector('#general-keep-alive-interval')
export const generalFindProcessMode = document.querySelector('#general-find-process-mode')
export const generalController = document.querySelector('#general-controller')
export const generalControllerTls = document.querySelector('#general-controller-tls')
export const generalControllerUnix = document.querySelector('#general-controller-unix')
export const generalControllerPipe = document.querySelector('#general-controller-pipe')
export const generalControllerCors = document.querySelector('#general-controller-cors')
export const generalUi = document.querySelector('#general-ui')
export const generalUiName = document.querySelector('#general-ui-name')
export const generalUiUrl = document.querySelector('#general-ui-url')
export const generalSecret = document.querySelector('#general-secret')
export const generalClientFingerprint = document.querySelector('#general-client-fingerprint')
export const generalUa = document.querySelector('#general-ua')
export const generalTlsCertificate = document.querySelector('#general-tls-certificate')
export const generalTlsPrivateKey = document.querySelector('#general-tls-private-key')
export const generalAllowLan = document.querySelector('#general-allow-lan')
export const generalIpv6 = document.querySelector('#general-ipv6')
export const generalDisableKeepAlive = document.querySelector('#general-disable-keep-alive')
export const generalUnifiedDelay = document.querySelector('#general-unified-delay')
export const generalTcpConcurrent = document.querySelector('#general-tcp-concurrent')
export const generalEtagSupport = document.querySelector('#general-etag-support')
export const profileStoreSelected = document.querySelector('#profile-store-selected')
export const profileStoreFakeIp = document.querySelector('#profile-store-fake-ip')
export const dnsEnhancedMode = document.querySelector('#dns-enhanced-mode')
export const dnsFakeIpRange = document.querySelector('#dns-fake-ip-range')
export const dnsFakeIpRange6 = document.querySelector('#dns-fake-ip-range6')
export const dnsFakeIpFilterMode = document.querySelector('#dns-fake-ip-filter-mode')
export const dnsFakeIpTtl = document.querySelector('#dns-fake-ip-ttl')
export const dnsFakeIpFilter = document.querySelector('#dns-fake-ip-filter')
export const dnsFallback = document.querySelector('#dns-fallback')
export const dnsFallbackFilter = document.querySelector('#dns-fallback-filter')
export const dnsDirectNameserver = document.querySelector('#dns-direct-nameserver')
export const dnsDirectFollowPolicy = document.querySelector('#dns-direct-follow-policy')
export const dnsProxyServer = document.querySelector('#dns-proxy-server')
export const dnsProxyPolicy = document.querySelector('#dns-proxy-policy')
export const dnsPolicy = document.querySelector('#dns-policy')
export const snifferEnable = document.querySelector('#sniffer-enable')
export const snifferOverride = document.querySelector('#sniffer-override')
export const snifferParseIp = document.querySelector('#sniffer-parse-ip')
export const snifferForceDnsMapping = document.querySelector('#sniffer-force-dns-mapping')
export const snifferSniff = document.querySelector('#sniffer-sniff')
export const snifferForce = document.querySelector('#sniffer-force')
export const snifferSkip = document.querySelector('#sniffer-skip')
export const snifferSkipSrc = document.querySelector('#sniffer-skip-src')
export const snifferSkipDst = document.querySelector('#sniffer-skip-dst')
export const tunEnable = document.querySelector('#tun-enable')
export const tunStack = document.querySelector('#tun-stack')
export const tunDevice = document.querySelector('#tun-device')
export const tunAutoRoute = document.querySelector('#tun-auto-route')
export const tunAutoRedirect = document.querySelector('#tun-auto-redirect')
export const tunAutoDetect = document.querySelector('#tun-auto-detect')
export const tunStrictRoute = document.querySelector('#tun-strict-route')
export const tunDnsHijack = document.querySelector('#tun-dns-hijack')
export const tunMtu = document.querySelector('#tun-mtu')
export const tunGso = document.querySelector('#tun-gso')
export const tunGsoMaxSize = document.querySelector('#tun-gso-max-size')
export const tunUdpTimeout = document.querySelector('#tun-udp-timeout')
export const tunIproute2TableIndex = document.querySelector('#tun-iproute2-table-index')
export const tunIproute2RuleIndex = document.querySelector('#tun-iproute2-rule-index')
export const tunEndpointIndependentNat = document.querySelector('#tun-endpoint-independent-nat')
export const tunRouteAddressSet = document.querySelector('#tun-route-address-set')
export const tunRouteExcludeAddressSet = document.querySelector('#tun-route-exclude-address-set')
export const tunRouteAddress = document.querySelector('#tun-route-address')
export const tunRouteExcludeAddress = document.querySelector('#tun-route-exclude-address')
export const tunIncludeInterface = document.querySelector('#tun-include-interface')
export const tunExcludeInterface = document.querySelector('#tun-exclude-interface')
export const tunIncludeUid = document.querySelector('#tun-include-uid')
export const tunIncludeUidRange = document.querySelector('#tun-include-uid-range')
export const tunExcludeUid = document.querySelector('#tun-exclude-uid')
export const tunExcludeUidRange = document.querySelector('#tun-exclude-uid-range')
export const tunIncludeAndroidUser = document.querySelector('#tun-include-android-user')
export const tunIncludePackage = document.querySelector('#tun-include-package')
export const tunExcludePackage = document.querySelector('#tun-exclude-package')
export const geoGeodataMode = document.querySelector('#geo-geodata-mode')
export const geoAutoUpdate = document.querySelector('#geo-auto-update')
export const geoGeodataLoader = document.querySelector('#geo-geodata-loader')
export const geoUpdateInterval = document.querySelector('#geo-update-interval')
export const geoUrlGeoip = document.querySelector('#geo-url-geoip')
export const geoUrlGeosite = document.querySelector('#geo-url-geosite')
export const geoUrlMmdb = document.querySelector('#geo-url-mmdb')
export const geoUrlAsn = document.querySelector('#geo-url-asn')
export const ruleProviderName = document.querySelector('#rule-provider-name')
export const ruleProviderUrl = document.querySelector('#rule-provider-url')
export const ruleProviderBehavior = document.querySelector('#rule-provider-behavior')
export const ruleProviderTarget = document.querySelector('#rule-provider-target')
export const ruleProviderFormat = document.querySelector('#rule-provider-format')
export const addRuleProviderButton = document.querySelector('#add-rule-provider-button')
export const addAdsProviderButton = document.querySelector('#add-ads-provider-button')
export const applyLanRulesButton = document.querySelector('#apply-lan-rules-button')
export const ruleProviderList = document.querySelector('#rule-provider-list')
export const ruleBuilderType = document.querySelector('#rule-builder-type')
export const ruleBuilderValue = document.querySelector('#rule-builder-value')
export const ruleBuilderTarget = document.querySelector('#rule-builder-target')
export const addRuleButton = document.querySelector('#add-rule-button')
export const proxyProviderName = document.querySelector('#proxy-provider-name')
export const proxyProviderUrl = document.querySelector('#proxy-provider-url')
export const proxyProviderType = document.querySelector('#proxy-provider-type')
export const addProxyProviderButton = document.querySelector('#add-proxy-provider-button')
export const proxyProviderList = document.querySelector('#proxy-provider-list')
export const manualNodeName = document.querySelector('#manual-node-name')
export const manualNodeType = document.querySelector('#manual-node-type')
export const manualNodeFields = document.querySelector('#manual-node-fields')
export const addManualNodeButton = document.querySelector('#add-manual-node-button')
export const nodeFilterQuery = document.querySelector('#node-filter-query')
export const nodeFilterType = document.querySelector('#node-filter-type')
export const openNodeToolsButton = document.querySelector('#open-node-tools-button')
export const nodeToolsSheet = document.querySelector('#node-tools-sheet')
export const closeNodeToolsButton = document.querySelector('#close-node-tools-button')
export const bulkRenamePattern = document.querySelector('#bulk-rename-pattern')
export const applyBulkRenameButton = document.querySelector('#apply-bulk-rename-button')
export const nodeSortField = document.querySelector('#node-sort-field')
export const sortNodesButton = document.querySelector('#sort-nodes-button')
export const deleteDuplicateNodesButton = document.querySelector('#delete-duplicate-nodes-button')
export const fabCopy = document.querySelector('#fab-copy')
export const fabDownload = document.querySelector('#fab-download')
export const toast = document.querySelector('#toast')
export const viewTabs = document.querySelectorAll('[data-view-target]')
export const viewPanels = document.querySelectorAll('.view-panel')
export const editTabs = document.querySelectorAll('[data-edit-target]')
export const editPanels = document.querySelectorAll('[data-edit-panel]')
export const editorSectionSelect = document.querySelector('#editor-section-select')

